[project]
name = "hello-kuzu-rdf"
version = "0.1.0"
requires-python = ">=3.11.8"
dependencies = [
    "chocolate==0.0.2",
    "icecream==2.1.3",
    "kuzu==0.6.1",
    "pandas==2.2.3",
    "pyshacl==0.29.0",
    "rdflib==7.1.1",
]
